In [4]:
import matplotlib.pyplot as plt
import numpy as np
import pandas as pd
import cvxpy as cp

In [16]:
lg = [31, 16, 25, 20, 4]
pk = ['off', 'mid', 'on', 'mid', 'off']
alpha = np.array([])
for i in range(len(lg)):
    if pk[i] == 'on':
        mult = 0.1079
    elif pk[i] == 'mid':
        mult = 0.0874
    elif pk[i] == 'off':
        mult = 0.0755
    alpha = np.append(alpha, (mult * np.ones(lg[i])))
alpha

array([0.0755, 0.0755, 0.0755, 0.0755, 0.0755, 0.0755, 0.0755, 0.0755,
       0.0755, 0.0755, 0.0755, 0.0755, 0.0755, 0.0755, 0.0755, 0.0755,
       0.0755, 0.0755, 0.0755, 0.0755, 0.0755, 0.0755, 0.0755, 0.0755,
       0.0755, 0.0755, 0.0755, 0.0755, 0.0755, 0.0755, 0.0755, 0.0874,
       0.0874, 0.0874, 0.0874, 0.0874, 0.0874, 0.0874, 0.0874, 0.0874,
       0.0874, 0.0874, 0.0874, 0.0874, 0.0874, 0.0874, 0.0874, 0.1079,
       0.1079, 0.1079, 0.1079, 0.1079, 0.1079, 0.1079, 0.1079, 0.1079,
       0.1079, 0.1079, 0.1079, 0.1079, 0.1079, 0.1079, 0.1079, 0.1079,
       0.1079, 0.1079, 0.1079, 0.1079, 0.1079, 0.1079, 0.1079, 0.1079,
       0.0874, 0.0874, 0.0874, 0.0874, 0.0874, 0.0874, 0.0874, 0.0874,
       0.0874, 0.0874, 0.0874, 0.0874, 0.0874, 0.0874, 0.0874, 0.0874,
       0.0874, 0.0874, 0.0874, 0.0874, 0.0755, 0.0755, 0.0755, 0.0755])

In [17]:
lg = [31, 16, 25, 20, 4]
pk = ['off', 'mid', 'on', 'mid', 'off']
val = [[0.1709, 0, 0], [0, 0.0874, 0], [0, 0, 0.0755]]
beta = {}
for i in range(len(val)):
    beta_i = np.array([])
    for j in range(len(lg)):
        if pk[j] == 'on':
            mult = val[0][i]
        elif pk[j] == 'mid':
            mult = val[1][i]
        elif pk[j] == 'off':
            mult = val[2][i]
        beta_i = np.append(beta_i, (mult * np.ones(lg[j])))
    beta[i] = beta_i
beta_ON = np.zeros((96, 96))
np.fill_diagonal(beta_ON, beta[0])
beta_MID = np.zeros((96, 96))
np.fill_diagonal(beta_MID, beta[1])
beta_OFF = np.zeros((96, 96))
np.fill_diagonal(beta_OFF, beta[2])

In [18]:
beta_ON

array([[0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       ...,
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.]])

In [19]:
beta_MID

array([[0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       ...,
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.]])

In [20]:
beta_OFF

array([[0.0755, 0.    , 0.    , ..., 0.    , 0.    , 0.    ],
       [0.    , 0.0755, 0.    , ..., 0.    , 0.    , 0.    ],
       [0.    , 0.    , 0.0755, ..., 0.    , 0.    , 0.    ],
       ...,
       [0.    , 0.    , 0.    , ..., 0.0755, 0.    , 0.    ],
       [0.    , 0.    , 0.    , ..., 0.    , 0.0755, 0.    ],
       [0.    , 0.    , 0.    , ..., 0.    , 0.    , 0.0755]])

In [7]:
df = pd.read_csv(r'/home/sigi_laptop/Documents/Research/NAPS_2023/Code/optimization_1084_2022_2023.csv')
df

time  solar    meter_load  building_load  opt_load  \
0      2022-03-01 00:00:00  -93.0 -18980.651823  -18887.651823    8078.5   
1      2022-03-01 00:15:00  -93.0 -21347.288021  -21254.288021    8078.5   
2      2022-03-01 00:30:00  -93.0 -20863.807031  -20770.807031    8078.5   
3      2022-03-01 00:45:00 -106.0 -21250.331901  -21144.331901    8078.5   
4      2022-03-01 01:00:00  -79.0 -20410.336589  -20331.336589    8078.5   
...                    ...    ...           ...            ...       ...   
35035  2023-02-28 22:45:00  -93.0 -20517.146615  -20424.146615   -6592.0   
35036  2023-02-28 23:00:00  -93.0 -20371.230339  -20278.230339   -6592.0   
35037  2023-02-28 23:15:00  -93.0 -20671.189193  -20578.189193   -6592.0   
35038  2023-02-28 23:30:00  -93.0 -20770.800651  -20677.800651   -6592.0   
35039  2023-02-28 23:45:00  -93.0 -20630.570573  -20537.570573   79555.0   

       opt_load_intplt  inverter_control  
0               8078.5     -27059.151823  
1               8078.5     -29425.788021  
2               8078.5     -28942.307031  
3               8078.5     -29328.831901  
4               8078.5     -28488.836589  
...                ...               ...  
35035          -6592.0     -13925.146615  
35036          -6592.0     -13779.230339  
35037          -6592.0     -14079.189193  
35038          -6592.0     -14178.800651  
35039          -6592.0     -14038.570573  

[35040 rows x 7 columns]

In [8]:
df.time = pd.to_datetime(df.time)

In [9]:
df['time_seconds'] = df.time.astype(int)

In [ ]:
df

In [ ]:
df.to_feather(r'/home/sigi_laptop/Documents/Research/NAPS_2023/Code/optimization_1084_2022_2023.feather')

In [ ]:
df.building_load.isnull().values.any()

In [25]:
load = abs(df.building_load.to_numpy() / 1000)
solar = abs(df.solar.to_numpy() / 1000)
load = load.astype(int)
solar = solar.astype(int)

eta_plus=0.96 # charging efficiency
eta_minus=0.96 # discharging efficiency
Emax=450 # SOC upper limit
Emin=100 # SOC lower limit
E_init=250 # initial state of charge
P_B_plus_max=100 # charging power limit
P_B_minus_max=100 # discharging power limit

opt_load=load #declaring optimal load
n=96 #declaring number of timestpes for each optimization
del_t=1/4 #time delta
d = 1 # int(len(load) / n )#number of days


# tou demand charge matrix
beta_OFF_val=1.53
beta_MID_val=3.13
beta_ON_val=7.06
pg = np.array([])
psl = np.array([])
eb = np.array([])
pbp = np.array([])
pbn = np.array([])
for i in range(d):
    cons = []
    P_S = solar[int(n*i) : int(n*i + n)]
    P_L = load[int(n*i) : int(n*i + n)]
    print(P_S)
    print(P_L)

    P_G = cp.Variable(n)
    E_B = cp.Variable(n)
    P_B_plus = cp.Variable(n)
    P_B_minus = cp.Variable(n)
    P_SL = cp.Variable(n)
 
    obj = cp.Minimize(alpha @ P_G * del_t + cp.max(beta_OFF @ P_G) + cp.max(beta_MID @ P_G) + cp.max(beta_ON @ P_G))
    for t in range(n):
        if t == 0:
           cons_temp = [
                E_B[t] == E_init,
                E_B[t] >= Emin,
                E_B[t] <= Emax,
                P_B_plus[t] >= 0,
                P_B_plus[t] <= P_B_plus_max,
                P_B_minus[t] >= 0,
                P_B_minus[t] <= P_B_minus_max,
                P_SL[t] + P_B_plus[t]/eta_plus == P_S[t],
                P_SL[t] + P_G[t] + P_B_minus[t]*eta_minus == P_L[t],
                P_SL[t] >= 0,
                #P_G[t] <= 100
            ]
           #print(cons_temp)
        else:
            cons_temp = [
                E_B[t] == E_B[t - 1] + del_t*(P_B_plus[t - 1] - P_B_minus[t - 1]),
                E_B[t] >= Emin,
                E_B[t] <= Emax,
                P_B_plus[t] >= 0,
                P_B_plus[t] <= P_B_plus_max,
                P_B_minus[t] >= 0,
                P_B_minus[t] <= P_B_minus_max,
                P_SL[t] + P_B_plus[t]/eta_plus == P_S[t],
                P_SL[t] + P_G[t] + P_B_minus[t]*eta_minus == P_L[t],
                P_SL[t] >= 0,
                #P_G[t] <= 100
            ]
        cons += cons_temp
    prob = cp.Problem(obj, cons)
    prob.solve(solver=cp.CBC, verbose = True, qcp = True)
    pg = np.append(pg, P_G.value)
    psl = np.append(psl, P_SL.value)
    eb = np.append(eb, E_B.value)
    pbp = np.append(pbp, P_B_plus.value)
    pbn = np.append(pbn, P_B_minus.value)
    
    E_init  = E_B[n - 1]
# print(prob.solve(solver=cp.SCS, verbose = True))
# print(prob.status)

[  0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0
   0   0   0   0   0   0   0   0   1   3   7  13  23  33  43  52  60  69
  77  84  90  95  83  76 100 100 100 100 100 100 100 100 100 100 100 100
 100 100 100 100  95  89  82  74  66  57  48  38  29  20  11   2   0   0
   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0
   0   0   0   0   0   0]
[18 21 20 21 20 22 21 21 20 16 16 16 16 15 17 15 16 15 16 16 16 16 16 16
 15 16 16 17 27 31 33 33 38 38 40 39 40 40 41 39 23 52 39 38 37 39 41 44
 48 42 47 46 46 46 46 50 50 50 50 50 50 50 50 50 50 50 50 43 43 41 33 36
 28 28 27 24 24 21 25 21 23 23 23 21 21 21 22 22 18 17 16 17 16 17 16 16]
                                     CVXPY                                     
                                     v1.3.1                                    
(CVXPY) Aug 01 11:55:28 AM: Your problem has 480 variables, 960 constraints, and 0 parameters.
(CVXPY) Aug 01 11:55:28 AM: It is compliant with the followin

In [39]:
pbp - pbn

array([  -2.08333333,   -5.20833333,   -4.16666667,   -5.20833333,
         -4.16666667,   -6.25      ,   -5.20833333,   -5.20833333,
         -4.16666667,    0.        ,    0.        ,    0.        ,
          0.        ,    0.        ,   -1.04166667,    0.        ,
          0.        ,    0.        ,    0.        ,    0.        ,
          0.        ,    0.        ,    0.        ,    0.        ,
          0.        ,    0.        ,    0.96      ,    1.92      ,
         -4.16666667,   -2.08333333,    5.76      ,   16.32      ,
         21.12      ,   29.76      ,   35.52      ,   45.12      ,
         11.83833333,   58.56      ,   63.36      ,   70.08      ,
         73.92      ,   39.36      ,   74.88      ,   75.84      ,
         76.8       ,   74.88      ,   72.96      ,    0.        ,
          0.        , -100.        , -100.        , -100.        ,
       -100.        , -100.        , -100.        , -100.        ,
       -100.        , -100.        , -100.        ,    0.     

In [38]:
pbn

array([  2.08333333,   5.20833333,   4.16666667,   5.20833333,
         4.16666667,   6.25      ,   5.20833333,   5.20833333,
         4.16666667,  -0.        ,  -0.        ,  -0.        ,
        -0.        ,  -0.        ,   1.04166667,  -0.        ,
        -0.        ,  -0.        ,  -0.        ,  -0.        ,
        -0.        ,  -0.        ,  -0.        ,  -0.        ,
        -0.        ,  -0.        ,  -0.        ,  -0.        ,
         4.16666667,   2.08333333,  -0.        ,  -0.        ,
        -0.        ,  -0.        ,  -0.        ,  -0.        ,
        -0.        ,  -0.        ,  -0.        ,  -0.        ,
        -0.        ,  -0.        ,  -0.        ,  -0.        ,
        -0.        ,  -0.        ,  -0.        ,  -0.        ,
        -0.        , 100.        , 100.        , 100.        ,
       100.        , 100.        , 100.        , 100.        ,
       100.        , 100.        , 100.        ,  -0.        ,
        -0.        ,  -0.        ,  -0.        ,  -0.  

In [ ]:
len(P_G.value)

In [ ]:
opt = pd.DataFrame({'pg' : pg, 'psl' : psl, 'eb' : eb, 'pbp': pbp, 'pbn' : pbn})
opt[opt.select_dtypes(include=['number']).columns] *= 1000
opt

In [ ]:
opt['ivt'] = (opt.pbn + opt.pbp)

In [ ]:
ivt.plot()

In [ ]:
localhost:888opt['time'] = df.time

In [ ]:
df

In [ ]:
import plotly.graph_objects as go
def plot_graph(x_data, y_data, line_name, title, x_title, y_title, filename, line_color, fig_show = False):
    # Define the figure
    fig = go.Figure()
    # Add data to figure
    for i in range(0, len(x_data), 1):
        fig.add_trace(go.Scattergl(x=x_data[i], y=y_data[i], name= line_name[i], line_color = line_color[i]))
            
    # Create Layout for the Html
    
    fig.update_layout(
        title=go.layout.Title(
            text= title,
            xref="paper",
            x=0.5
        ),
        xaxis=go.layout.XAxis(
            title=go.layout.xaxis.Title(
                text=x_title,
            ),
            rangeslider=dict(
                visible=True
            )
        ),
        yaxis=go.layout.YAxis(
            title=go.layout.yaxis.Title(
                text=y_title,
            )
        )
    )
    
    fig.write_html((filename + '.html'), include_mathjax='cdn')
    fig = go.Figure()
    # Add data to figure
    for i in range(0, len(x_data), 1):
        fig.add_trace(go.Scatter(x=x_data[i], y=y_data[i], name= line_name[i], line_color = line_color[i]))
    fig.update_layout(
        title=go.layout.Title(
            text= title,
            xref="paper",
            x=0.5
        ),
        xaxis=go.layout.XAxis(
            title=go.layout.xaxis.Title(
                text=x_title,
            ),
            rangeslider=dict(
                visible=False
            )
        ),
        yaxis=go.layout.YAxis(
            title=go.layout.yaxis.Title(
                text=y_title,
            )
        )
    )
    fig.write_image(filename + '.svg', engine = 'orca')
    fig.write_image(filename + '.pdf', engine = 'orca')
    # fig.write_image(filename + '.png') Do not use png in your code this is only an example to compare png to vector images
    if fig_show:
        fig.show()

In [ ]:
x_title = "Time"
y_title = "Demand (kW)"
line_name = ["Opt Load", "Load"]
line_color = ["deepskyblue", "red"]
x_data = [opt.time] * 2
y_data = [df.building_load  + opt.ivt, df.building_load]
site_name_t = "1084 CVXPy Optimized Load Output"
plot_type_t = "15 Minute Data"
site_name_f = "1084_opt_BESS"
plot_type_f = "15_Minute_Data"
title = site_name_t + "<br>" + plot_type_t + "<br>From: " +  df.time.min().strftime('%B %d, %Y') + " to " + df.time.max().strftime('%B %d, %Y') 
filename = site_name_f + '_' + plot_type_f + '_' + df.time.min().strftime('%b_%d_%Y') + "_to_" + df.time.max().strftime('%b_%d_%Y') 
plot_graph(x_data, y_data, line_name, title, x_title, y_title, filename, line_color, fig_show = True)

In [ ]:
opt.eb[:96*3].plot()

In [ ]:
((-1 * opt.pg) + df.building_load + df.solar).plot()

In [ ]:
(df.building_load + df.solar - opt.pg).plot()

In [ ]:
df.building_load.plot()

In [ ]:
(df.building_load + df.solar).plot()

In [ ]:
opt.pg[:96].plot()

In [ ]:
(df.building_load[:96] - df.solar[:96]).plot()

In [ ]:
df.building_load[:96].plot()

In [ ]:
10 % 3

In [ ]:
x = 2
y = 3
mg_mo_output = pd.DataFrame({'load' : [x], 'solar' : [y]})
mg_mo_output

In [ ]:
mg_mo_output.loc[len(mg_mo_output.index)] = [4, 5] 
mg_mo_output

In [ ]:
int((86400 * 2.6) / 86400)

In [79]:
def tou_cvx_one_day(dblInp):
    import numpy as np
    import pandas as pd
    import cvxpy as cp
    import os
    
    [net_load, solar, SOC, time] = dblInp
    num_first_iterations = 96 * 900
    epoch_timeshift = 1646092800
    #df = pd.read_feather('optimization_1084_2022_2023.feather')
    
    if time == 0:
        # Create and overwrite microgrid output dataframe for simulation
        ivt_ctrl = 0
        e_init = pd.DataFrame({'e_init': [250]})
        e_init.to_feather('e_init.feather')
        mg_mo_output = pd.DataFrame({'day': [0], 'net_load' : [net_load], 'SOC' : [SOC], 'solar' : [solar]})
        mg_mo_output.to_feather('mg_mo_output.feather')
        return(ivt_ctrl)
    elif time < num_first_iterations:
        # No prior data run optimization as zero
        ivt_ctrl = 0
        num_day =  int(time / 86400)
        mg_mo_output = pd.read_feather('mg_mo_output.feather')
        mg_mo_output.loc[len(mg_mo_output.index)] = [num_day, net_load, SOC, solar]
        mg_mo_output.to_feather('mg_mo_output.feather')
        return(ivt_ctrl)
    
    elif time % num_first_iterations == 0:
        # New iteration (usually a day)
        # Run optimzation run for that day and save output as a feather file
        num_day =  int(time / 86400)
        mg_mo_output = pd.read_feather('mg_mo_output.feather')
        mg_mo_output.loc[len(mg_mo_output.index)] = [num_day, net_load, SOC, solar]
        mg_mo_output.to_feather('mg_mo_output.feather')
        
        lg = [31, 16, 25, 20, 4]
        pk = ['off', 'mid', 'on', 'mid', 'off']
        alpha = np.array([])
        for i in range(len(lg)):
            if pk[i] == 'on':
                mult = 0.1079
            elif pk[i] == 'mid':
                mult = 0.0874
            elif pk[i] == 'off':
                mult = 0.0755
            alpha = np.append(alpha, (mult * np.ones(lg[i])))


        lg = [31, 16, 25, 20, 4]
        pk = ['off', 'mid', 'on', 'mid', 'off']
        val = [[0.1709, 0, 0], [0, 0.0874, 0], [0, 0, 0.0755]]
        beta = {}
        for i in range(len(val)):
            beta_i = np.array([])
            for j in range(len(lg)):
                if pk[j] == 'on':
                    mult = val[0][i]
                elif pk[j] == 'mid':
                    mult = val[1][i]
                elif pk[j] == 'off':
                    mult = val[2][i]
                beta_i = np.append(beta_i, (mult * np.ones(lg[j])))
            beta[i] = beta_i
        beta_ON = np.zeros((96, 96))
        np.fill_diagonal(beta_ON, beta[0])
        beta_MID = np.zeros((96, 96))
        np.fill_diagonal(beta_MID, beta[1])
        beta_OFF = np.zeros((96, 96))
        np.fill_diagonal(beta_OFF, beta[2])

#         load = abs(df.building_load.to_numpy() / 1000)
#         solar = abs(df.solar.to_numpy() / 1000)
#         load = load.astype(int)
#         solar = solar.astype(int)
#         load = load[:96]
#         solar = solar[:96]

        eta_plus=0.96 # charging efficiency
        eta_minus=0.96 # discharging efficiency
        Emax=450 # SOC upper limit
        Emin=100 # SOC lower limit
        e_init = pd.read_feather('e_init.feather')
        E_init= e_init.e_init[0] # initial state of charge
        P_B_plus_max=100 # charging power limit
        P_B_minus_max=100 # discharging power limit

#        opt_load=load #declaring optimal load
        n=96 #declaring number of timestpes for each optimization
        del_t=1/4 #time delta



        # tou demand charge matrix
        beta_OFF_val=1.53
        beta_MID_val=3.13
        beta_ON_val=7.06
        pg = np.array([])
        psl = np.array([])
        eb = np.array([])
        pbp = np.array([])
        pbn = np.array([])
        
        cons = []

        P_S = abs((mg_mo_output['solar'][mg_mo_output['day'] == num_day - 1] / 1000))
        P_L = abs((mg_mo_output['net_load'][mg_mo_output['day'] == num_day - 1] / 1000))
        P_S = P_S.astype(int)
        P_L = P_L.astype(int)
        d = int(len(P_L) / n )#number of days

        P_G = cp.Variable(n)
        E_B = cp.Variable(n)
        P_B_plus = cp.Variable(n)
        P_B_minus = cp.Variable(n)
        P_SL = cp.Variable(n)

        obj = cp.Minimize(alpha @ P_G * del_t + cp.max(beta_OFF @ P_G) + cp.max(beta_MID @ P_G) + cp.max(beta_ON @ P_G))
        for t in range(n):
            if t == 0:
               cons_temp = [
                    E_B[t] == E_init,
                    E_B[t] >= Emin,
                    E_B[t] <= Emax,
                    P_B_plus[t] >= 0,
                    P_B_plus[t] <= P_B_plus_max,
                    P_B_minus[t] >= 0,
                    P_B_minus[t] <= P_B_minus_max,
                    P_SL[t] + P_B_plus[t]/eta_plus == P_S[t],
                    P_SL[t] + P_G[t] + P_B_minus[t]*eta_minus == P_L[t],
                    P_SL[t] >= 0
                ]
               #print(cons_temp)
            else:
                cons_temp = [
                    E_B[t] == E_B[t - 1] + del_t*(P_B_plus[t - 1] - P_B_minus[t - 1]),
                    E_B[t] >= Emin,
                    E_B[t] <= Emax,
                    P_B_plus[t] >= 0,
                    P_B_plus[t] <= P_B_plus_max,
                    P_B_minus[t] >= 0,
                    P_B_minus[t] <= P_B_minus_max,
                    P_SL[t] + P_B_plus[t]/eta_plus == P_S[t],
                    P_SL[t] + P_G[t] + P_B_minus[t]*eta_minus == P_L[t],
                    P_SL[t] >= 0
                ]
            cons += cons_temp
        prob = cp.Problem(obj, cons)
        prob.solve(solver=cp.SCS, verbose = True, qcp = True)
        pg = np.append(pg, P_G.value)
        psl = np.append(psl, P_SL.value)
        eb = np.append(eb, E_B.value)
        pbp = np.append(pbp, P_B_plus.value)
        pbn = np.append(pbn, P_B_minus.value)
        E_init  = E_B[n - 1]
        e_init = pd.DataFrame({'e_init': [E_init.value]})
        e_init.to_feather('e_init.feather')
        opt_output = pd.DataFrame({'opt': pbp - pbn})
        opt_output.to_feather('opt_output.feather')
        ivt_ctrl = opt_output.opt[0]
        return (ivt_ctrl)    
    else:
        # On the same iteration (usually within a day)
        # Read the feather file and output the data
        opt_output = 'opt_output.feather'
        minute_15 = 900 # number of seconds in 15 minutes
        if os.path.exists(opt_output):
            opt_output = pd.read_feather(opt_output)
            iter_day = (time % num_first_iterations) / minute_15
            ivt_ctrl =  opt_output.opt[iter_day]
        num_day =  int(time / 86400)
        mg_mo_output = pd.read_feather('mg_mo_output.feather')
        mg_mo_output.loc[len(mg_mo_output.index)] = [num_day, net_load, SOC, solar]
        mg_mo_output.to_feather('mg_mo_output.feather')
        return (ivt_ctrl)

In [80]:
for i in range(100):
    tou_cvx_one_day([abs(df.building_load[i]), abs(df.solar[i]), 0.5, i * 900])

                                     CVXPY                                     
                                     v1.3.1                                    
(CVXPY) Aug 01 02:03:02 PM: Your problem has 480 variables, 960 constraints, and 0 parameters.
(CVXPY) Aug 01 02:03:02 PM: It is compliant with the following grammars: DCP, DQCP
(CVXPY) Aug 01 02:03:02 PM: (If you need to solve this problem multiple times, but with different data, consider using parameters.)
(CVXPY) Aug 01 02:03:02 PM: CVXPY will first compile your problem; then, it will invoke a numerical solver to obtain a solution.
-------------------------------------------------------------------------------
                                  Compilation                                  
-------------------------------------------------------------------------------
(CVXPY) Aug 01 02:03:02 PM: Compiling problem (target solver=SCS).
(CVXPY) Aug 01 02:03:02 PM: Reduction chain: Dcp2Cone -> CvxAttr2Constr -> ConeMatrixStuffing 